//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaptorDb
{
    using System;
    using System.Collections.Generic;
    using FacesLib;

    public partial class Face
    {
        public long Id { get; set; }
        public string COFace { get; set; }
        public long COId { get; set; }
    
        public virtual ContentObject ContentObject { get; set; }

        
    }
}
