//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaptorDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RaptorEntities : DbContext
    {
        public RaptorEntities()
            : base("name=RaptorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARecord> ARecords { get; set; }
        public virtual DbSet<ContentObject> ContentObjects { get; set; }
        public virtual DbSet<COSource> COSources { get; set; }
        public virtual DbSet<CRecord> CRecords { get; set; }
        public virtual DbSet<Face> Faces { get; set; }
        public virtual DbSet<OnlineHistory> OnlineHistories { get; set; }
        public virtual DbSet<ProcessedBy> ProcessedBies { get; set; }
        public virtual DbSet<RankHistory> RankHistories { get; set; }
        public virtual DbSet<Rank> Ranks { get; set; }
        public virtual DbSet<RRecord> RRecords { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Url> Urls { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkRecord> WorkRecords { get; set; }
    }
}
