//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaptorDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Url
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Url()
        {
            this.ARecords = new HashSet<ARecord>();
            this.CRecords = new HashSet<CRecord>();
            this.RRecords = new HashSet<RRecord>();
            this.ProcessedBies = new HashSet<ProcessedBy>();
        }
    
        public long Id { get; set; }
        public string URLPath { get; set; }
        public string URLHash { get; set; }
        public bool Processed { get; set; }
        public Nullable<long> ProcessedById { get; set; }
        public long FoundById { get; set; }
        public System.DateTime FoundOn { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
        public bool IsContentObject { get; set; }
        public double ResponseCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARecord> ARecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRecord> CRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RRecord> RRecords { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessedBy> ProcessedBies { get; set; }
    }
}
